"""Render deterministic Markdown API shards and offline web data from api-index.json."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
import uuid
from collections import defaultdict
from pathlib import Path
from typing import Any


GENERATED = "<!-- Generated by scripts/render_docs.py. Do not edit directly. -->"


def plain_slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-") or "root"


def slug(value: str) -> str:
    base = plain_slug(value)
    digest = hashlib.sha256(value.encode("utf-8")).hexdigest()[:12]
    return f"{base}-{digest}"


def java_literal(value: Any, java_type: str) -> str:
    if java_type == "boolean":
        return "true" if value else "false"
    if java_type == "char" and isinstance(value, int):
        code = value & 0xFFFF
        escapes = {8: "\\b", 9: "\\t", 10: "\\n", 12: "\\f", 13: "\\r", 39: "\\'", 92: "\\\\"}
        rendered = escapes.get(code, chr(code) if 0x20 <= code <= 0x7E else f"\\u{code:04x}")
        return f"'{rendered}'"
    if java_type == "java.lang.String" and isinstance(value, str):
        return json.dumps(value, ensure_ascii=True, allow_nan=False)
    if java_type == "long" and isinstance(value, int):
        return f"{value}L"
    if java_type in {"float", "double"} and isinstance(value, str):
        owner = "Float" if java_type == "float" else "Double"
        suffix = {"NaN": "NaN", "Infinity": "POSITIVE_INFINITY", "-Infinity": "NEGATIVE_INFINITY"}[value]
        return f"{owner}.{suffix}"
    if java_type == "float" and isinstance(value, (int, float)):
        return f"{value!r}f"
    return repr(value)


def signature(member: dict[str, Any]) -> str:
    mods = " ".join(value for value in member["modifiers"] if value not in {"bridge", "synthetic"})
    if member["kind"] == "field":
        result = f"{mods} {member['return_type']} {member['name']}"
        if member["constant"] is not None:
            result += f" = {java_literal(member['constant'], member['return_type'])}"
        return result.strip()
    params = ", ".join(member["parameters"])
    if member["kind"] == "constructor":
        result = f"{mods} {member['name']}({params})"
    else:
        result = f"{mods} {member['return_type']} {member['name']}({params})"
    if member["throws"]:
        result += " throws " + ", ".join(member["throws"])
    return result.strip()


def class_lines(record: dict[str, Any]) -> list[str]:
    title = record["name"].rsplit(".", 1)[-1]
    lines = [f"## `{title}`", "", f"- Stable ID: `{record['id']}`", f"- Origin: `{record.get('origin', 'plugin-owned')}`", f"- Kind: `{record['visibility']} {record['kind']}`"]
    if record["super"]:
        lines.append(f"- Extends: `{record['super']}`")
    if record["interfaces"]:
        lines.append("- Implements: " + ", ".join(f"`{value}`" for value in record["interfaces"]))
    lines.extend([f"- Bytecode: Java class major `{record['major_version']}`; entry `{record['jar_entry']}`"])
    if record.get("source_path"):
        lines.append(f"- Decompiled source: `{record['source_path']}`")
    lines.extend(["", "| Kind | Visibility | Signature | JVM descriptor |", "|---|---|---|---|"])
    if not record["members"]:
        lines.append("| - | - | No public/protected members | - |")
    for member in record["members"]:
        rendered = signature(member).replace("|", "\\|")
        descriptor = member["descriptor"].replace("|", "\\|")
        lines.append(f"| {member['kind']} | {member['visibility']} | `{rendered}` | `{descriptor}` |")
    lines.append("")
    return lines


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8", newline="\n")


def strict_json(path: Path) -> Any:
    def reject(value: str) -> None:
        raise ValueError(f"Non-standard JSON constant {value} in {path}")

    return json.loads(path.read_text(encoding="utf-8"), parse_constant=reject)


def paths_overlap(first: Path, second: Path) -> bool:
    first, second = first.resolve(), second.resolve()
    return first == second or first in second.parents or second in first.parents


def assert_unique_slugs(values: list[str], label: str) -> None:
    seen: dict[str, str] = {}
    for value in values:
        encoded = slug(value).casefold()
        if encoded in seen and seen[encoded] != value:
            raise ValueError(f"Filename collision for {label}: {seen[encoded]!r} and {value!r}")
        seen[encoded] = value


def reset_generated_dir(target: Path, parent: Path) -> None:
    """Delete only the known generated child directory, never its parent."""
    resolved_target = assert_safe_generated_path(target, parent)
    if resolved_target.exists():
        shutil.rmtree(resolved_target)


def assert_safe_generated_path(target: Path, parent: Path) -> Path:
    """Return the resolved child path after rejecting escapes and reparse points."""
    resolved_target = target.resolve()
    resolved_parent = parent.resolve()
    if resolved_target == resolved_parent or resolved_parent not in resolved_target.parents:
        raise ValueError(f"Refusing unsafe generated path: {resolved_target}")
    is_junction = getattr(target, "is_junction", None)
    if target.is_symlink() or (is_junction is not None and is_junction()):
        raise ValueError(f"Refusing generated reparse point: {target}")
    return resolved_target


def reset_generated_file(target: Path, parent: Path) -> None:
    """Delete only a known generated child file, never a directory or its parent."""
    resolved_target = assert_safe_generated_path(target, parent)
    if resolved_target.exists():
        if resolved_target.is_dir():
            raise ValueError(f"Refusing to reset generated file path containing a directory: {resolved_target}")
        resolved_target.unlink()


def reset_generated_path(target: Path, parent: Path, is_directory: bool) -> None:
    if is_directory:
        reset_generated_dir(target, parent)
    else:
        reset_generated_file(target, parent)


def publish_render_transaction(outputs: list[tuple[Path, Path, Path, bool]]) -> None:
    """Atomically publish staged outputs, retaining every old snapshot until commit."""
    transaction_id = uuid.uuid4().hex
    operations: list[dict[str, Any]] = []
    for stage, target, parent, is_directory in outputs:
        assert_safe_generated_path(stage, parent)
        assert_safe_generated_path(target, parent)
        if not stage.exists() or stage.is_dir() != is_directory:
            raise ValueError(f"Invalid staged render output: {stage}")
        if target.exists() and target.is_dir() != is_directory:
            raise ValueError(f"Existing render output has unexpected type: {target}")
        backup = parent / f".{target.name}-backup-{transaction_id}"
        assert_safe_generated_path(backup, parent)
        if backup.exists():
            raise ValueError(f"Render backup already exists: {backup}")
        operations.append({
            "stage": stage,
            "target": target,
            "parent": parent,
            "backup": backup,
            "is_directory": is_directory,
            "had_target": target.exists(),
            "promoted": False,
        })

    try:
        for operation in operations:
            if operation["had_target"]:
                operation["target"].replace(operation["backup"])
            operation["stage"].replace(operation["target"])
            operation["promoted"] = True
    except Exception as publication_error:
        rollback_errors: list[str] = []
        for operation in reversed(operations):
            try:
                backup_exists = operation["backup"].exists()
                target_exists = operation["target"].exists()
                stage_exists = operation["stage"].exists()
                if backup_exists:
                    if target_exists:
                        reset_generated_path(operation["target"], operation["parent"], operation["is_directory"])
                    operation["backup"].replace(operation["target"])
                elif not operation["had_target"] and target_exists and (operation["promoted"] or not stage_exists):
                    reset_generated_path(operation["target"], operation["parent"], operation["is_directory"])
            except Exception as rollback_error:
                rollback_errors.append(f"{operation['target']}: {rollback_error}")
        for operation in operations:
            try:
                if operation["stage"].exists():
                    reset_generated_path(operation["stage"], operation["parent"], operation["is_directory"])
            except Exception as cleanup_error:
                rollback_errors.append(f"{operation['stage']}: {cleanup_error}")
        if rollback_errors:
            details = "; ".join(rollback_errors)
            raise RuntimeError(f"Render publication failed and rollback was incomplete: {details}") from publication_error
        raise
    for operation in operations:
        if operation["backup"].exists():
            reset_generated_path(operation["backup"], operation["parent"], operation["is_directory"])


def render_plugin_docs(root: Path, plugin: dict[str, Any], max_lines: int) -> list[dict[str, Any]]:
    plugin_slug = slug(plugin["name"])
    target = root / plugin_slug
    packages: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for record in plugin["classes"]:
        packages[record["package"]].append(record)
    assert_unique_slugs(list(packages), f"{plugin['name']} packages")
    links, shards = [], []
    for package, records in sorted(packages.items()):
        chunk, part, current = [], 1, [GENERATED, f"# {plugin['name']} API: `{package}`", "", "Factual signatures extracted from JVM metadata. Decompiled source is supporting evidence only.", ""]
        for record in records:
            addition = class_lines(record)
            if chunk and len(current) + len(addition) > max_lines:
                filename = f"{slug(package)}-part-{part:02d}.md"
                write(target / filename, "\n".join(current))
                shards.append({"package": package, "file": filename, "types": len(chunk)})
                part, chunk = part + 1, []
                current = [GENERATED, f"# {plugin['name']} API: `{package}` (part {part})", ""]
            current.extend(addition)
            chunk.append(record)
        filename = f"{slug(package)}-part-{part:02d}.md"
        write(target / filename, "\n".join(current))
        shards.append({"package": package, "file": filename, "types": len(chunk)})
    for item in shards:
        links.append(f"| `{item['package']}` | [{item['file']}](./{item['file']}) | {item['types']} |")
    plugin_owned = [value for value in plugin["classes"] if value.get("origin", "plugin-owned") == "plugin-owned"]
    bundled = len(plugin["classes"]) - len(plugin_owned)
    index_lines = [GENERATED, f"# {plugin['name']} API", "", f"- JAR: `{plugin['jar']}`", f"- Namespace: `{', '.join(plugin['namespace_prefixes'])}`", f"- Public/protected types: **{len(plugin['classes']):,}** ({len(plugin_owned):,} plugin-owned; {bundled:,} bundled third-party)", f"- Public/protected members: **{sum(len(value['members']) for value in plugin['classes']):,}**", "", "| Package | Shard | Types |", "|---|---|---:|", *links]
    write(target / "index.md", "\n".join(index_lines))
    return shards


def render_web_data(web: Path, plugins: list[dict[str, Any]]) -> dict[str, Any]:
    data_root = web / "data"
    manifest = {"schemaVersion": 1, "plugins": []}
    ui_slugs = [plain_slug(plugin["name"]).casefold() for plugin in plugins]
    if len(ui_slugs) != len(set(ui_slugs)):
        raise ValueError("Plugin names collide after UI slug normalization")
    for plugin in plugins:
        name_slug = plain_slug(plugin["name"])
        filename = f"{slug(plugin['name'])}.js"
        compact = json.dumps(plugin, ensure_ascii=False, separators=(",", ":"), allow_nan=False)
        write(data_root / filename, f"window.MinecraftRPGKit.registerPlugin({compact});")
        owned_classes = [value for value in plugin["classes"] if value.get("origin", "plugin-owned") == "plugin-owned"]
        manifest["plugins"].append({
            "name": plugin["name"], "slug": name_slug, "file": f"data/{filename}",
            "types": len(plugin["classes"]), "members": sum(len(value["members"]) for value in plugin["classes"]),
            "pluginOwnedTypes": len(owned_classes),
            "pluginOwnedMembers": sum(len(value["members"]) for value in owned_classes),
            "namespaces": plugin["namespace_prefixes"],
        })
    write(data_root / "manifest.js", "window.MinecraftRPGManifest=" + json.dumps(manifest, ensure_ascii=False, separators=(",", ":"), allow_nan=False) + ";")
    return manifest


def render_web_insights(payload: dict[str, Any], web: Path, manifest: dict[str, Any]) -> None:
    write(web / "data" / "insights.js", "window.MinecraftRPGInsights=" + json.dumps(payload, ensure_ascii=False, separators=(",", ":"), allow_nan=False) + ";")
    manifest["insightsFile"] = "data/insights.js"
    write(web / "data" / "manifest.js", "window.MinecraftRPGManifest=" + json.dumps(manifest, ensure_ascii=False, separators=(",", ":"), allow_nan=False) + ";")


def load_insights(data: Path) -> dict[str, Any]:
    plugin_path = data / "plugin-insights.json"
    feature_path = data / "feature-catalog.json"
    addon_path = data / "addon-ideas.json"
    plugin_records = strict_json(plugin_path)["plugins"] if plugin_path.is_file() else []
    feature_records = strict_json(feature_path)["domains"] if feature_path.is_file() else []
    addon_records = strict_json(addon_path)["ideas"] if addon_path.is_file() else []
    plugin_blocks: dict[str, Any] = {}
    for plugin in plugin_records:
        plugin_blocks[plugin["name"]] = {
            "overview": {
                "title": f"{plugin['name']} {plugin['version']}",
                "intro": plugin["role"],
                "source": "Curated bytecode and source review",
                "items": [
                    {"title": "API boundaries", "body": plugin["api_boundaries"], "meta": plugin["family"]},
                    {"title": "Engineering patterns", "body": plugin["patterns"], "meta": "DERIVED_SOURCE"},
                    {"title": "Review risks", "body": plugin["risks"], "meta": "Runtime validation required"},
                ],
            },
            "architecture": {
                "title": f"{plugin['name']} architecture",
                "intro": plugin["architecture"],
                "source": "Curated source-derived architecture",
                "items": [
                    {"title": "Extension boundaries", "body": plugin["api_boundaries"], "meta": "Prefer explicit API and events"},
                    {"title": "Evidence", "body": plugin["evidence"], "meta": "Relative decompiled paths"},
                    {"title": "Operational risks", "body": plugin["risks"], "meta": "UNVERIFIED where noted"},
                ],
            },
            "features": {
                "title": f"{plugin['name']} capabilities",
                "intro": "Capability groups identified in the reviewed artifact. Query exact symbols before implementation.",
                "source": "Curated plugin feature catalog",
                "items": [{"title": value, "body": f"Search the {plugin['name']} API shard for exact types and members.", "meta": plugin["name"]} for value in plugin["capabilities"]],
            },
        }
    payload: dict[str, Any] = {
        "schemaVersion": 1,
        "plugins": plugin_blocks,
        "global": {
            "features": {
                "title": "Cross-plugin RPG feature domains",
                "intro": "Capability compositions with explicit state ownership and safety constraints.",
                "source": "Curated feature catalog",
                "items": [{"title": item["name"], "body": item["composition"], "meta": item["owners"]} for item in feature_records],
            },
            "addons": {
                "title": "Original addon blueprints",
                "intro": "New compositions inferred from reviewed extension points, not existing vendor features.",
                "source": "MinecraftRPG Kit ORIGINAL_DESIGN catalog",
                "items": [{"title": item["title"], "body": item["new_behavior"], "meta": [item["maturity"], *item["plugins"]]} for item in addon_records],
            },
        },
    }
    coverage_path = data / "api-coverage.json"
    if coverage_path.is_file():
        coverage = strict_json(coverage_path)["plugins"]
        payload["stats"] = {
            "totalTypes": sum(item["published_types"] for item in coverage),
            "totalMembers": sum(item["published_members"] for item in coverage),
            "pluginOwnedTypes": sum(item.get("plugin_owned_types", item["published_types"]) for item in coverage),
            "pluginOwnedMembers": sum(item.get("plugin_owned_members", item["published_members"]) for item in coverage),
        }
    return payload


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, required=True)
    parser.add_argument("--docs", type=Path, required=True)
    parser.add_argument("--web", type=Path, required=True)
    parser.add_argument("--max-lines", type=int, default=760)
    args = parser.parse_args()
    if args.max_lines < 100 or args.max_lines > 800:
        parser.error("--max-lines must be between 100 and 800")
    data, docs, web = args.data.resolve(), args.docs.resolve(), args.web.resolve()
    api_root, web_data = docs / "api", web / "data"
    for first_name, first, second_name, second in (("data", data, "docs/api", api_root), ("data", data, "web/data", web_data), ("docs/api", api_root, "web/data", web_data)):
        if paths_overlap(first, second):
            parser.error(f"Unsafe path overlap between {first_name} ({first}) and {second_name} ({second})")

    index = strict_json(data / "api-index.json")
    insight_payload = load_insights(data)
    assert_unique_slugs([plugin["name"] for plugin in index["plugins"]], "plugins")
    docs.mkdir(parents=True, exist_ok=True)
    web.mkdir(parents=True, exist_ok=True)
    api_stage = docs / f".api-stage-{uuid.uuid4().hex}"
    web_stage_root = web / f".web-stage-{uuid.uuid4().hex}"
    manifest_stage = data / f".docs-manifest-stage-{uuid.uuid4().hex}.json"
    global_rows, shard_manifest = [], {}
    try:
        api_stage.mkdir()
        web_stage_root.mkdir()
        for plugin in index["plugins"]:
            shards = render_plugin_docs(api_stage, plugin, args.max_lines)
            shard_manifest[plugin["name"]] = shards
            owned_classes = [value for value in plugin["classes"] if value.get("origin", "plugin-owned") == "plugin-owned"]
            global_rows.append(f"| {plugin['name']} | [{slug(plugin['name'])}](./{slug(plugin['name'])}/index.md) | {len(owned_classes):,} | {len(plugin['classes']) - len(owned_classes):,} | {sum(len(value['members']) for value in plugin['classes']):,} |")
        write(api_stage / "index.md", "\n".join([GENERATED, "# Complete Plugin API Catalog", "", "Bytecode-derived public/protected signature inventory. No implementation bodies are included. Bundled third-party namespace records remain searchable but are labeled so they are not misattributed to plugin developers.", "", "| Plugin | API | Plugin-owned types | Bundled types | All members |", "|---|---|---:|---:|---:|", *global_rows]))
        web_manifest = render_web_data(web_stage_root, index["plugins"])
        render_web_insights(insight_payload, web_stage_root, web_manifest)
        if not (api_stage / "index.md").is_file() or len(list((web_stage_root / "data").glob("*.js"))) != len(index["plugins"]) + 2:
            raise ValueError("Staged render failed output validation")
        write(manifest_stage, json.dumps({"schema_version": 1, "plugins": shard_manifest}, indent=2, sort_keys=True, ensure_ascii=False, allow_nan=False))
        publish_render_transaction([
            (web_stage_root / "data", web_data, web, True),
            (api_stage, api_root, docs, True),
            (manifest_stage, data / "docs-manifest.json", data, False),
        ])
    finally:
        if api_stage.exists():
            reset_generated_dir(api_stage, docs)
        if web_stage_root.exists():
            reset_generated_dir(web_stage_root, web)
        if manifest_stage.exists():
            reset_generated_file(manifest_stage, data)
    print(f"Rendered {sum(len(value) for value in shard_manifest.values())} Markdown shards and {len(web_manifest['plugins'])} web shards")
    return 0


if __name__ == "__main__":
    sys.exit(main())
